/* edge_machine.c: the edge automaton in C, with the wall generated by the label recursion.

   The window machine of edge_automaton.py: diagonals d-1, d on rows [M_d - W, M_d + TOP] and one input
   bit D_{d+1}(M_d - W) per diagonal give D_{d+1} on the window by
       D_{d+1}(t+1) = D_{d-1}(t) xor (D_d(t) or D_{d+1}(t)),
   solved bit-parallel as a prefix over the maps x -> e xor (m and x) (e = D_{d-1} xor D_d, m = not D_d);
   the new diagonal settles where it last differs from its background r_{d+1}; the front is the running
   maximum M_{d+1} = max(M_d, tau_{d+1} - 1).  Labels are 128-bit periodic words (bit t = r(t mod 128)),
   the next label the fixed point of c -> rotl(a ^ b ^ (~b & c), 1) (Lemma 18.2), and at a frozen diagonal
   (r_d = 0) the branch is read from the machine's own cell D_{d+1}(M_d + 1) (ledger 10.231d I(ii)-(iii)).
   Input modes: coin (splitmix64, one bit per diagonal), zero, one.  Crystal start at row M0.
   Records: the front, offers and decisions (the m = 2 and m = 3 context tables, offers and moves capped
   at 16), the jump and stall histograms, per-block speeds, and every frozen diagonal met with the
   branch taken and M_d mod 128.
   Usage: edge_machine A_HEX B_HEX D0 D1 W TOP MODE SEED M0 OUTPREFIX [BLOCK] [MDUMP]
     MODE: coin | coin:P (P = probability of a 1) | zero | one; MDUMP: file receiving M_d per diagonal (int64)
     the three-event table is written only with EDGE_TAB3=1 in the environment (10 MB per process)
     A_HEX, B_HEX: r_{D0-1}, r_{D0} (16 or 32 hex digits as wall_recursion128.c prints them)
     OUTPREFIX.txt gets the report, OUTPREFIX.tab2 / .tab3 the context tables (uint64), OUTPREFIX.blocks
     the per-block statistics.  edge_machine --selftest checks the prefix solver against the sequential
     recurrence on random windows.  M0 = 0 means 4 D0 / 3. */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

typedef unsigned __int128 u128;
#define NW 5                       /* window words: up to 320 rows */
typedef struct { uint64_t w[NW]; } vec;

static inline u128 rotl128(u128 x, int k) { k &= 127; return k ? (x << k) | (x >> (128 - k)) : x; }
static inline u128 rotr128(u128 x, int k) { k &= 127; return k ? (x >> k) | (x << (128 - k)) : x; }
static int period128(u128 x) { int p = 128; while (p > 1 && rotl128(x, p / 2) == x) p /= 2; return p; }
static int popcount128(u128 x) { return __builtin_popcountll((uint64_t)x) + __builtin_popcountll((uint64_t)(x >> 64)); }
static u128 parse_hex(const char *s) {
    u128 v = 0; size_t n = strlen(s);
    for (; *s; s++) { int c = *s | 32; int d = (c >= '0' && c <= '9') ? c - '0' : c - 'a' + 10; v = (v << 4) | (u128)d; }
    if (n <= 16) v |= v << 64;
    return v;
}
static void print128(FILE *f, u128 x) { fprintf(f, "%016llx%016llx", (unsigned long long)(x >> 64), (unsigned long long)x); }

/* ---- bit vectors of n rows ---- */
static int n_rows;
static inline void vzero(vec *v) { memset(v, 0, sizeof *v); }
static inline int vget(const vec *v, int i) { return (v->w[i >> 6] >> (i & 63)) & 1; }
static inline void vset(vec *v, int i, int b) { if (b) v->w[i >> 6] |= 1ULL << (i & 63); else v->w[i >> 6] &= ~(1ULL << (i & 63)); }
static void vshl(vec *d, const vec *s, int k) {          /* d = s << k (row i -> row i + k) */
    vec t; vzero(&t); int wq = k >> 6, wr = k & 63;
    for (int i = NW - 1; i >= wq; i--) {
        uint64_t x = s->w[i - wq] << wr;
        if (wr && i - wq - 1 >= 0) x |= s->w[i - wq - 1] >> (64 - wr);
        t.w[i] = x;
    }
    *d = t;
}
static void vshr(vec *d, const vec *s, int k) {          /* d = s >> k (row i -> row i - k) */
    vec t; vzero(&t); int wq = k >> 6, wr = k & 63;
    for (int i = 0; i + wq < NW; i++) {
        uint64_t x = s->w[i + wq] >> wr;
        if (wr && i + wq + 1 < NW) x |= s->w[i + wq + 1] << (64 - wr);
        t.w[i] = x;
    }
    *d = t;
}
static void vmask(vec *v) {                              /* clear rows >= n_rows */
    for (int i = 0; i < NW; i++) {
        int lo = i * 64;
        if (lo >= n_rows) v->w[i] = 0;
        else if (lo + 64 > n_rows) v->w[i] &= (1ULL << (n_rows - lo)) - 1;
    }
}
static void bg_vec(vec *v, u128 word, long long t0) {   /* v[i] = r(t0 + i), r the periodic word */
    u128 r = rotr128(word, (int)(((t0 % 128) + 128) % 128));   /* bit i = r(t0 + i) for i < 128 */
    uint64_t lo = (uint64_t)r, hi = (uint64_t)(r >> 64);
    for (int i = 0; i < NW; i++) v->w[i] = (i & 1) ? hi : lo;    /* period 128 = two words, repeated */
    vmask(v);
}

/* new diagonal on the window: prefix solver (Kogge-Stone) over f_i(x) = e_i ^ (m_i & x) */
static void solve_prefix(const vec *prev, const vec *cur, int input, vec *out) {
    vec e, m, A, M, t1, t2;
    for (int i = 0; i < NW; i++) { e.w[i] = prev->w[i] ^ cur->w[i]; m.w[i] = ~cur->w[i]; }
    vshl(&A, &e, 1); vshl(&M, &m, 1); M.w[0] |= 1ULL;
    for (int k = 1; k < n_rows; k <<= 1) {
        vshl(&t1, &A, k); vshl(&t2, &M, k);
        for (int i = 0; i < NW; i++) {
            uint64_t low = 0;
            if (i == 0) low = (k >= 64) ? ~0ULL : ((1ULL << k) - 1);
            else if (i * 64 < k) low = (i * 64 + 64 <= k) ? ~0ULL : ((1ULL << (k - i * 64)) - 1);
            A.w[i] ^= M.w[i] & t1.w[i];
            M.w[i] &= (t2.w[i] | low);
        }
    }
    for (int i = 0; i < NW; i++) out->w[i] = A.w[i] ^ (input ? M.w[i] : 0);
    vmask(out);
}
static void solve_seq(const vec *prev, const vec *cur, int input, vec *out) {
    vzero(out); int x = input; vset(out, 0, x);
    for (int i = 1; i < n_rows; i++) { x = vget(prev, i - 1) ^ (vget(cur, i - 1) | x); vset(out, i, x); }
}

/* ---- labels ---- */
static u128 next_label(u128 a, u128 b) {                 /* b != 0 */
    u128 z = ~b; int L = 0; while (z) { z &= rotl128(z, 1); L++; }
    u128 c = 0; for (int k = 0; k <= L; k++) c = rotl128(a ^ b ^ (~b & c), 1);
    return c;
}
static u128 frozen_X(u128 a) {                           /* X(t) = xor_{s<t} a(s) */
    u128 X = 0; int x = 0;
    for (int t = 0; t < 128; t++) { if (x) X |= (u128)1 << t; x ^= (int)((a >> t) & 1); }
    return X;
}

/* ---- rng ---- */
static uint64_t rng_s;
static inline uint64_t splitmix() { uint64_t z = (rng_s += 0x9e3779b97f4a7c15ULL); z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL; z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL; return z ^ (z >> 31); }

int main(int argc, char **argv) {
    if (argc > 1 && !strcmp(argv[1], "--selftest")) {
        rng_s = 12345; int bad = 0;
        for (int trial = 0; trial < 20000; trial++) {
            n_rows = 3 + (int)(splitmix() % 300);
            vec p, c, o1, o2; vzero(&p); vzero(&c);
            for (int i = 0; i < NW; i++) { p.w[i] = splitmix(); c.w[i] = splitmix(); if (splitmix() & 1) c.w[i] &= splitmix(); }
            vmask(&p); vmask(&c);
            int in = splitmix() & 1;
            solve_prefix(&p, &c, in, &o1); solve_seq(&p, &c, in, &o2);
            if (memcmp(&o1, &o2, sizeof o1)) bad++;
        }
        printf("selftest: 20000 random windows of 3..302 rows, %d mismatches between the prefix solver and the sequential recurrence\n", bad);
        return bad != 0;
    }
    if (argc < 11) { fprintf(stderr, "usage: edge_machine A_HEX B_HEX D0 D1 W TOP MODE SEED M0 OUTPREFIX [BLOCK]\n"); return 2; }
    u128 a = parse_hex(argv[1]), b = parse_hex(argv[2]);
    long long D0 = atoll(argv[3]), D1 = atoll(argv[4]);
    int W = atoi(argv[5]), TOP = atoi(argv[6]);
    const char *mode = argv[7]; uint64_t seed = strtoull(argv[8], 0, 10);
    long long M0 = atoll(argv[9]); const char *out = argv[10];
    long long BLOCK = argc > 11 ? atoll(argv[11]) : 100000000LL;
    n_rows = W + TOP + 1;
    if (n_rows > 64 * NW) { fprintf(stderr, "window too tall for NW=%d words\n", NW); return 2; }
    int imode = !strncmp(mode, "coin", 4) ? 0 : !strcmp(mode, "zero") ? 1 : 2;
    double pone = 0.5; if (imode == 0 && mode[4] == ':') pone = atof(mode + 5);     /* coin:P gives P(input = 1) = P */
    uint64_t pthresh = (uint64_t)(pone * 18446744073709551615.0);
    FILE *mdump = argc > 12 ? fopen(argv[12], "wb") : NULL;
    rng_s = seed * 0x2545F4914F6CDD1DULL + 0x1234567ULL;
    char fn[512]; snprintf(fn, sizeof fn, "%s.txt", out); FILE *rep = fopen(fn, "w");
    snprintf(fn, sizeof fn, "%s.blocks", out); FILE *blk = fopen(fn, "w");
    fprintf(blk, "# block_start block_end moves rows_gained speed\n");
    /* tables: tab2[s2][s1][g][dec], tab3[s3][s2][s1][g][dec]; symbols 0..33 (2*min(g,16)+dec), g 0..16 */
    static uint64_t tab2[34][34][17][2]; static uint64_t tab3[34][34][34][17][2];
    int use_tab3 = getenv("EDGE_TAB3") != NULL;         /* the 10 MB three-event table only on request (cache) */
    uint64_t ctx3[2] = {0, 0};                          /* the open three-event context W1, M1, M3, offer 1 */
    static uint64_t jhist[400], khist[400];
    long long M = M0 ? M0 : 4 * D0 / 3, t0 = M - W;
    vec prev, cur, nw, bgv, tmp;
    bg_vec(&prev, a, t0); bg_vec(&cur, b, t0);            /* crystal start */
    fprintf(rep, "start d=%lld M=%lld W=%d TOP=%d mode=%s seed=%llu; a=", D0, M, W, TOP, mode, (unsigned long long)seed); print128(rep, a);
    fprintf(rep, " (p=%d) b=", period128(a)); print128(rep, b); fprintf(rep, " (p=%d)\n", period128(b));
    long long moves = 0, gained = 0, stall = 0, Mstart = M, bstart_M = M, bstart_d = D0, bmoves = 0;
    int s1 = -1, s2 = -1, s3 = -1;                         /* last three symbols */
    int last_move = 0; long long waits_since = 0, n_long = 0, n_tight = 0, src2[4] = {0, 0, 0, 0};
    uint64_t rbits = 0; int rleft = 0;
    for (long long d = D0; d < D1; d++) {
        /* offer: first 1 of r_d above M_d */
        int g = 0;
        if (b) { u128 r = rotr128(b, (int)(((M + 1) % 128 + 128) % 128)); uint64_t lo = (uint64_t)r, hi = (uint64_t)(r >> 64);
                 g = lo ? __builtin_ctzll(lo) + 1 : (hi ? __builtin_ctzll(hi) + 65 : 0); }
        /* input bit */
        int input;
        if (imode == 0) {
            if (pone == 0.5) { if (!rleft) { rbits = splitmix(); rleft = 64; } input = rbits & 1; rbits >>= 1; rleft--; }
            else input = splitmix() < pthresh;
        } else input = (imode == 2);
        solve_prefix(&prev, &cur, input, &nw);
        /* next label */
        u128 c; int beta = -1;
        if (b == 0) {
            u128 X = frozen_X(a);
            int frozen_odd = (int)(popcount128(a) & 1);
            if (frozen_odd) { fprintf(rep, "d=%lld: frozen diagonal with 128-bit odd parity: period 256, stop\n", d); break; }
            int cell = vget(&nw, (int)(M + 1 - t0));
            beta = cell ^ (int)((X >> ((M + 1) & 127)) & 1);
            c = beta ? ~X : X;
            fprintf(rep, "d=%lld: frozen diagonal, p_(d-1)=%d weight %d, branch %d taken (M_d=%lld, M_d mod 128 = %lld, period of the new label %d)\n",
                    d, period128(a), popcount128(a) / (128 / period128(a)), beta, M, ((M % 128) + 128) % 128, period128(c));
            fflush(rep);
        } else c = next_label(a, b);
        /* settling: last row where the new diagonal differs from its background r_{d+1} */
        bg_vec(&bgv, c, t0);
        int last = -1;
        for (int i = NW - 1; i >= 0; i--) { uint64_t x = nw.w[i] ^ bgv.w[i]; if (x) { last = i * 64 + 63 - __builtin_clzll(x); break; } }
        long long tau_new = last >= 0 ? t0 + last + 1 : t0;
        long long Mnew = tau_new - 1 > M ? tau_new - 1 : M;
        if (Mnew - M > TOP - 2) { fprintf(rep, "d=%lld: jump %lld exceeds the window (TOP=%d): stop\n", d, Mnew - M, TOP); fclose(rep); return 1; }
        int dec = Mnew > M;
        /* C27 bookkeeping: a move of J >= 2 is tight when the back stripe r_{d-1} is white on the jumped rows
           M+1..M+J-2 and black on M+J-1 (the landing row is free); runs of >= 2 waits are attributed to the move */
        if (dec) {
            long long J = Mnew - M;
            if (J == 1) last_move = 1;
            else {
                u128 r = rotr128(a, (int)(((M + 1) % 128 + 128) % 128));
                u128 seg = (J - 1 >= 128) ? r : (r & (((u128)1 << (J - 1)) - 1));   /* rows M+1 .. M+J-1 */
                int tight = (seg == ((u128)1 << (J - 2)));                                /* black on M+J-1 only */
                last_move = tight ? 2 : 3; n_long++; n_tight += tight;
            }
            waits_since = 0;
        } else if (last_move) {
            waits_since++;
            if (waits_since == 2) src2[last_move]++;
        }
        /* statistics */
        int gc = g > 16 ? 16 : g; int sym = 2 * gc + dec;
        if (s2 >= 0) tab2[s2][s1][gc][dec]++;
        if (s3 >= 0) { if (use_tab3) tab3[s3][s2][s1][gc][dec]++; if (s3 == 2 && s2 == 3 && s1 == 7 && gc == 1) ctx3[dec]++; }
        s3 = s2; s2 = s1; s1 = sym;
        if (dec) { long long J = Mnew - M; moves++; gained += J; bmoves++; if (J < 400) jhist[J]++; if (stall < 400) khist[stall]++; stall = 0; }
        else stall++;
        /* shift the window */
        long long s = Mnew - M;
        if (s) {
            vshr(&tmp, &cur, (int)s); bg_vec(&bgv, b, t0 + n_rows); vshl(&bgv, &bgv, (int)(n_rows - s)); vmask(&bgv);
            for (int i = 0; i < NW; i++) prev.w[i] = tmp.w[i] | bgv.w[i];
            vshr(&tmp, &nw, (int)s); bg_vec(&bgv, c, t0 + n_rows); vshl(&bgv, &bgv, (int)(n_rows - s)); vmask(&bgv);
            for (int i = 0; i < NW; i++) cur.w[i] = tmp.w[i] | bgv.w[i];
        } else { prev = cur; cur = nw; }
        M = Mnew; t0 = M - W; a = b; b = c;
        if (mdump) fwrite(&M, sizeof M, 1, mdump);
        if ((d + 1 - D0) % BLOCK == 0 || d + 1 == D1) {
            fprintf(blk, "%lld %lld %lld %lld %.6f\n", bstart_d, d + 1, bmoves, M - bstart_M, (double)(M - bstart_M) / (double)(d + 1 - bstart_d));
            fflush(blk); bstart_d = d + 1; bstart_M = M; bmoves = 0;
        }
    }
    long long D = D1 - D0;
    fprintf(rep, "diagonals %lld: speed %.6f, P(move) %.6f, mean move %.6f\n", D, (double)(M - Mstart) / D, (double)moves / D, moves ? (double)gained / moves : 0.0);
    fprintf(rep, "jump histogram:"); for (int j = 1; j < 400; j++) if (jhist[j]) fprintf(rep, " %d:%llu", j, (unsigned long long)jhist[j]); fprintf(rep, "\n");
    fprintf(rep, "stall histogram:"); for (int k = 0; k < 400; k++) if (khist[k]) fprintf(rep, " %d:%llu", k, (unsigned long long)khist[k]); fprintf(rep, "\n");
    fprintf(rep, "C27: moves of 2+ rows %lld, tight %lld (%.4f); runs of 2+ waits after a one-row move %lld, after a tight move %lld, after a non-tight move of 2+ %lld (must be 0)\n",
            n_long, n_tight, n_long ? (double)n_tight / n_long : 0.0, src2[1], src2[2], src2[3]);
    { long long k2 = 0, kall = 0; for (int k = 0; k < 400; k++) { kall += khist[k]; if (k >= 2) k2 += khist[k]; }
      fprintf(rep, "bad share (stall runs of 2+ waits per cycle): %lld / %lld = %.5f\n", k2, kall, kall ? (double)k2 / kall : 0.0); }
    fprintf(rep, "context W1 M1 M3 offer 1: waits %llu moves %llu\n", (unsigned long long)ctx3[0], (unsigned long long)ctx3[1]);
    fprintf(rep, "final M=%lld labels a=", M); print128(rep, a); fprintf(rep, " b="); print128(rep, b); fprintf(rep, "\n");
    fclose(rep); fclose(blk); if (mdump) fclose(mdump);
    snprintf(fn, sizeof fn, "%s.tab2", out); FILE *f2 = fopen(fn, "wb"); fwrite(tab2, sizeof tab2, 1, f2); fclose(f2);
    if (use_tab3) { snprintf(fn, sizeof fn, "%s.tab3", out); FILE *f3 = fopen(fn, "wb"); fwrite(tab3, sizeof tab3, 1, f3); fclose(f3); }
    return 0;
}
